### ISSUE TITLE
ERROR  : Exception in thread "main" com.google.inject.ConfigurationException: Guice configuration errors:

### ISSUE THREAD

**Issue by srinvias** [lucidworks/hadoop-solr#6]
Hi,

Thank you for wonderfull help in solr hadoop documentation. i build the code using maven .

i am getting below error while executing. please help me . Thanks .

```java
Exception in thread "main" com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for com.lucidworks.hadoop.io.LWDocument was bound.
  while locating com.lucidworks.hadoop.io.LWDocument
1 error
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:961)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
        at com.lucidworks.hadoop.io.LWDocumentProvider.init(LWDocumentProvider.java:25)
        at com.lucidworks.hadoop.ingest.AbstractJobFixture.init(AbstractJobFixture.java:20)
        at com.lucidworks.hadoop.ingest.CSVIngestMapper$1.init(CSVIngestMapper.java:45)
        at com.lucidworks.hadoop.ingest.IngestJob.run(IngestJob.java:204)
```

**Comment by acesar** [comment]
> i build the code using maven .

@srinvias are you changing the build process from gradle to maven? 

The implementation of `LWDocument`needs to be specify in the file `/META-INF/services/com.lucidworks.hadoop.io.LWDocument`  
check: https://github.com/lucidworks/solr-hadoop-common/blob/master/solr-hadoop-document/src/main/resources/META-INF/services/com.lucidworks.hadoop.io.LWDocument

check if your jar has that file.
